In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.4'

## Armando arreglos

In [3]:
np.array([0, 1, 2, 3, 4, 5])

array([0, 1, 2, 3, 4, 5])

In [4]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [5]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(4, dtype=np.int32)

array([1, 1, 1, 1], dtype=int32)

## Forma de trabajo

In [8]:
clasica = list(range(10))
clasica

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
nueva = np.arange(10)
nueva

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
[x ** 2 for x in clasica]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [11]:
np.array([x ** 2 for x in nueva])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
nueva

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
nueva ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Evaluación de velocidad

In [14]:
def f():
    clasica = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    cuads = [x ** 2 for x in clasica]
 
def g():
    nueva = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    cuads = nueva ** 2

print("Método clásico:")
%timeit f()
print("Usando numpy:")
%timeit g()

Método clásico:
1.73 µs ± 9.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
Usando numpy:
1.79 µs ± 17.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [15]:
def f():
    clasica = range(1_000_000)
    cuads = [x ** 2 for x in clasica]

def g():
    nueva = np.arange(1_000_000)
    cuads = nueva ** 2
    
print("Método clásico:")
%timeit f()
print("Usando numpy:")
%timeit g()

Método clásico:
190 ms ± 2.34 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Usando numpy:
1.97 ms ± 65.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


### Las operaciones siempre a través de NumPy

In [16]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr.max()

9

In [18]:
arr.sum()

45

In [19]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

### Multidimensionalidad

In [20]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.ones((2, 2, 5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### Formas, tamaños y dimensiones

In [22]:
lineal = np.arange(20)
lineal

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
lineal.shape

(20,)

In [24]:
matriz = lineal.reshape((2, 2, 5))
matriz

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [25]:
matriz.shape

(2, 2, 5)

In [26]:
lineal.ndim

1

In [27]:
matriz.ndim

3

In [28]:
lineal.size

20

In [29]:
matriz.size

20

### Accediendo a elementos y sub-arreglos

In [30]:
lineal[4]

4

In [31]:
lineal[:4]

array([0, 1, 2, 3])

In [32]:
matriz.shape

(2, 2, 5)

In [33]:
subm = matriz[0]
subm.shape

(2, 5)

In [34]:
subm

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
matriz[1][0][3]

13

In [36]:
matriz[1,0,3]

13

In [37]:
matriz

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [38]:
matriz[:]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [39]:
matriz[:, 1:]

array([[[ 5,  6,  7,  8,  9]],

       [[15, 16, 17, 18, 19]]])

In [40]:
matriz[:, 1:, 2]

array([[ 7],
       [17]])

In [41]:
matriz[:, 1:, 2].shape

(2, 1)

### Copias y referencias

In [42]:
l1 = [1, 2, 3, 4]
l2 = l1[:2]
l2

[1, 2]

In [43]:
l1[0] = 7
l2

[1, 2]

In [44]:
l2[1] = 9
l1

[7, 2, 3, 4]

In [45]:
a1 = np.array([1, 2, 3, 4])
a2 = a1[:2]
a2

array([1, 2])

In [46]:
a1[0] = 7
a2

array([7, 2])

In [47]:
a2[1] = 9
a1

array([7, 9, 3, 4])

## Indización avanzada

### Con un arreglo de números

In [48]:
cuadrados = np.arange(20) ** 2
cuadrados

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [49]:
índice = [2, 3, 15, 7]
cuadrados[índice]

array([  4,   9, 225,  49])

In [50]:
cuadrados[[0, 1, 2, 3, 2, 1, 0]]

array([0, 1, 4, 9, 4, 1, 0])

### Con un arreglo de booleanos

In [51]:
nros = np.array([0, 1, 2, 3, 4])
índice = [True, False, False, True, False]
nros[índice]

array([0, 3])

### Ejemplo más real de un arreglo-índice de booleanos, sacando logaritmos de números

In [52]:
nros = np.random.randint(-10, 10, 20)
nros

array([ -2,   3,   9,  -4,  -1,  -1,   0,   3,  -6,   0,   6,   2,   2,
         3,   4,  -6,   2,   6,  -5, -10])

In [53]:
cuales_positivos = nros > 0
cuales_positivos

array([False,  True,  True, False, False, False, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False])

In [54]:
positivos = nros[cuales_positivos]
positivos

array([3, 9, 3, 6, 2, 2, 3, 4, 2, 6])

In [55]:
np.log(positivos)

array([1.09861229, 2.19722458, 1.09861229, 1.79175947, 0.69314718,
       0.69314718, 1.09861229, 1.38629436, 0.69314718, 1.79175947])

### Ordenamos dos arreglos correlacionados

In [56]:
x = np.array([7, 3, 5, 9, 0, 6, 4, 1, 2, 8])
y = np.array([-8,  1, -3, -2,  3,  6,  5, -3,  2,  9])
índice = np.argsort(x)
índice  # este nos dejaría a X ordenado

array([4, 7, 8, 1, 6, 2, 5, 0, 9, 3])

In [57]:
x[índice]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
y[índice]

array([ 3, -3,  2,  1,  5, -3,  6, -8,  9, -2])

## Broadcasting

In [59]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([7, 6, 5, 4, 3])
x + y

array([7, 7, 7, 7, 7])

In [60]:
x * y

array([ 0,  6, 10, 12, 12])

### Operando entre un arreglo y un escalar, y su equivalente

In [61]:
x = np.array([0, 1, 2, 3, 4])
x * 2

array([0, 2, 4, 6, 8])

In [62]:
x = np.array([0, 1, 2, 3, 4])
x * np.array([2, 2, 2, 2, 2])

array([0, 2, 4, 6, 8])

### Ejemplo operando con una foto

In [63]:
foto = np.arange(12).reshape((2, 2, 3))  # 2x2 pixeles, x 3 valores para RGB
foto

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [64]:
filtro = np.array([.01, 1., 1.])  # solamente bajamos rojo muchísimo
filtro

array([0.01, 1.  , 1.  ])

In [65]:
# mostramos las formas alineadas a la izquierda
print("foto  : {:>6s}".format(' '.join(str(x) for x in foto.shape)))
print("filtro: {:>6s}".format(' '.join(str(x) for x in filtro.shape)))

foto  :  2 2 3
filtro:      3


In [66]:
foto * filtro

array([[[ 0.  ,  1.  ,  2.  ],
        [ 0.03,  4.  ,  5.  ]],

       [[ 0.06,  7.  ,  8.  ],
        [ 0.09, 10.  , 11.  ]]])

In [67]:
np.broadcast_to(filtro, foto.shape)

array([[[0.01, 1.  , 1.  ],
        [0.01, 1.  , 1.  ]],

       [[0.01, 1.  , 1.  ],
        [0.01, 1.  , 1.  ]]])

### Con más dimensiones

In [68]:
nros = np.arange(8).reshape((2, 4))
nros

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [69]:
nros.shape

(2, 4)

In [70]:
factor = np.array([[3], [5]])
factor

array([[3],
       [5]])

In [71]:
factor.shape

(2, 1)

In [72]:
nros * factor

array([[ 0,  3,  6,  9],
       [20, 25, 30, 35]])

### Ejemplo más complicado

In [73]:
n1 = np.arange(12).reshape((2, 1, 2, 3))
n1

array([[[[ 0,  1,  2],
         [ 3,  4,  5]]],


       [[[ 6,  7,  8],
         [ 9, 10, 11]]]])

In [74]:
n2 = np.array([100, 200, 300, 400, 500, 600]).reshape((2, 1, 3))
n2

array([[[100, 200, 300]],

       [[400, 500, 600]]])

In [75]:
n1 + n2

array([[[[100, 201, 302],
         [103, 204, 305]],

        [[400, 501, 602],
         [403, 504, 605]]],


       [[[106, 207, 308],
         [109, 210, 311]],

        [[406, 507, 608],
         [409, 510, 611]]]])

## Vectores y matrices

### Usando el operador `*`

In [76]:
nros = np.array([0, 1, 2, 3, 4])
nros * 3

array([ 0,  3,  6,  9, 12])

In [77]:
nros1 = np.array([2, 3, 4])
nros2 = np.array([10, 0, 20])
nros1 * nros2

array([20,  0, 80])

In [78]:
mat = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
nros = np.array([10, 20, 30])
mat * nros

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

### Multiplicando matrices

In [79]:
nros1 = np.array([2, 3, 4])
nros2 = np.array([10, 0, 20])
nros1 @ nros2

100

In [80]:
mat = np.array([[30, 10], [40, 40], [50, 50]])  # 2 columnas
mat

array([[30, 10],
       [40, 40],
       [50, 50]])

In [81]:
vec = np.array([1, 2])  # largo 2
vec

array([1, 2])

In [82]:
mat @ vec  # el resultado es largo 2 como el vector

array([ 50, 120, 150])

In [83]:
mat1 = np.array([[1, 1, 1], [2, 2, 2]])
mat1

array([[1, 1, 1],
       [2, 2, 2]])

In [84]:
mat2 = np.array([[30, 10], [40, 40], [50, 50]])
mat2

array([[30, 10],
       [40, 40],
       [50, 50]])

In [85]:
mat1 @ mat2

array([[120, 100],
       [240, 200]])

### Otras operaciones de álgebra lineal

In [86]:
mat1 = np.array([[1, 2], [3, 4]])
np.linalg.det(mat1)

-2.0000000000000004

In [87]:
mat2 = np.array([[6, 2, 3], [1, -2, 0], [12, 2, -1]])
np.linalg.det(mat2)

92.00000000000001

In [88]:
np.linalg.inv(mat1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [89]:
np.linalg.inv(mat2)

array([[ 0.02173913,  0.08695652,  0.06521739],
       [ 0.01086957, -0.45652174,  0.0326087 ],
       [ 0.2826087 ,  0.13043478, -0.15217391]])

In [90]:
np.linalg.norm(mat1)

5.477225575051661

In [91]:
np.linalg.norm(mat2)

14.247806848775006

### Resolución de sistemas de ecuaciones

In [92]:
A = np.array([[3, 1, 0], [0, 4, -1], [1, 3, -2]])
A

array([[ 3,  1,  0],
       [ 0,  4, -1],
       [ 1,  3, -2]])

In [93]:
b = np.array([-3, 5, -7])
b

array([-3,  5, -7])

In [94]:
x = np.linalg.solve(A, b)
x

array([-2.,  3.,  7.])

In [95]:
A @ x

array([-3.,  5., -7.])

In [96]:
A @ x == b

array([False,  True, False])

In [97]:
(A @ x)[0]

-3.0000000000000004

In [98]:
(A @ x)[0] == .3

False


### Copyright 2020-2024 Facundo Batista y Manuel Carlevaro

Licencia CC BY-NC-SA 4.0

Para más info visitar: https://github.com/facundobatista/libro-pyciencia/

