In [1]:
import numpy as np

y = [1, 2, 3, 4, 5]
x1 = [6, 7, 8, 9, 10]
x2 = [13, 14, 15, 16, 17]
data = {'y': np.array(y), 'x1': np.array(x1), 'x2': np.array(x2)}

In [2]:
from patsy import dmatrices

dmatrices("y ~ x1 + x2 + x1:x2", data)

(DesignMatrix with shape (5, 1)
   y
   1
   2
   3
   4
   5
   Terms:
     'y' (column 0),
 DesignMatrix with shape (5, 4)
   Intercept  x1  x2  x1:x2
           1   6  13     78
           1   7  14     98
           1   8  15    120
           1   9  16    144
           1  10  17    170
   Terms:
     'Intercept' (column 0)
     'x1' (column 1)
     'x2' (column 2)
     'x1:x2' (column 3))

In [3]:
from patsy import dmatrix

X = dmatrix("x1 + x2 + x1:x2")
X

DesignMatrix with shape (5, 4)
  Intercept  x1  x2  x1:x2
          1   6  13     78
          1   7  14     98
          1   8  15    120
          1   9  16    144
          1  10  17    170
  Terms:
    'Intercept' (column 0)
    'x1' (column 1)
    'x2' (column 2)
    'x1:x2' (column 3)

In [4]:
print(type(X))
print(X)

<class 'patsy.design_info.DesignMatrix'>
[[  1.   6.  13.  78.]
 [  1.   7.  14.  98.]
 [  1.   8.  15. 120.]
 [  1.   9.  16. 144.]
 [  1.  10.  17. 170.]]


In [5]:
import pandas as pd

df_data = pd.DataFrame(data)
y, X = dmatrices("y ~x1 + x2 + x1:x2", df_data, return_type="dataframe")
X

Intercept    x1    x2  x1:x2
0        1.0   6.0  13.0   78.0
1        1.0   7.0  14.0   98.0
2        1.0   8.0  15.0  120.0
3        1.0   9.0  16.0  144.0
4        1.0  10.0  17.0  170.0

In [6]:
beta, res, rank, sval = np.linalg.lstsq(X, y, rcond=None)
beta

array([[-3.33333333e-01],
       [ 1.66666667e+00],
       [-6.66666667e-01],
       [-4.44089210e-16]])


### Copyright 2020-2024 Facundo Batista y Manuel Carlevaro

Licencia CC BY-NC-SA 4.0

Para más info visitar: https://github.com/facundobatista/libro-pyciencia/

